sudo: false
dist: trusty

language: cpp
compiler:
  - clang
  - gcc
  
cache: ccache

branches:
  only:
  - master

git:
  depth: 1

env:
  - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - kubuntu-backports
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libtool
      - gcc-4.8
      - g++-4.8
      - make
      - cmake
      - libboost1.55-dev
      - libboost-system1.55-dev
      - libboost-program-options1.55-dev
      - libboost-thread1.55-dev
      - libboost-regex1.55-dev

# overwrite GCC version for GCC build only
before_install:
  - if [ $CC = "gcc" ] ; then export CC=gcc-4.8 CXX=g++-4.8 ; fi
  - mkdir _build
  - mkdir _install
  - cd _build
  - export CCACHE_SLOPPINESS=pch_defines,time_macros
  - cmake -DCMAKE_INSTALL_PREFIX=../_install -DBUILD_EXTRACTORS=ON -DPCH=$PCH_FLAG ..

script:
  - make -j 4 && make install
